version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      
      - run:
          name: Install Dependencies
          command: npm install

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
            
          paths:
            - ./node_modules          

      - run:
          name: Gatsby Build
          command: npm run build

  deploy-test:
    working_directory: ~/repo

    docker: 
      - image: circleci/node:8

    steps:     
      - run:
          name: Firebase Deploy Test
          command: npm run deploy:test:ci
  
  deploy-prod:
    working_directory: ~/repo

    docker: 
      - image: circleci/node:8

    steps:     
      - run:
          name: Firebase Deploy Prod
          command: npm run deploy:prod:ci

workflows:
  version: 2
  deploy_test_prod:
    jobs:
      - build
      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: develop

      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master
